version: '3.8'
services:
  fastapi:
    build: './app/.'
    container_name: back-end
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on: 
      - db
  
  frontend:
    build: './frontend/.'
    container_name: front-end
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    expose:
      - 3000
    command: npm run dev

  db:
    image: postgres:13
    restart: 'always'
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pinterest_db:/var/lib/postgresql/data/
    env_file:
    - .env

  
volumes:
  pinterest_db:
  